services:
  mosquitto:
    build:
      context: ./mosquitto
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
        - linux/arm64
    container_name: mosquitto
    image: kkanho/mosquitto:latest
    ports:
      - "1883:1883"  # MQTT port
      - "9001:9001"  # Websocket port (optional)
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    networks:
      - web-iot-network
  api: # backend
    build: 
      context: ./api
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
        - linux/arm64
      args:
        NODE_ENV: development
    container_name: backend-fastapi
    image: kkanho/api:latest
    ports:
      - "8000:8000"
      - "5678:5678" # debugpy
    volumes:
      - ./api:/usr/src/api
    environment:
      - CHOKIDAR_USEPOLLING=true # hot reload
    # restart: always
    networks:
      - web-iot-network
    depends_on:
      - mosquitto
  app: # frontend
    build: 
      context: ./app
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
        - linux/arm64
      args:
        NODE_ENV: development
    container_name: frontend-react
    image: kkanho/app:latest
    ports:
      - "3000:3000"
    volumes:
      - ./app:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true # hot reload
    networks:
      - web-iot-network
    depends_on:
      - api
      - mosquitto

networks:
  web-iot-network:
    driver: bridge